language: python
sudo: false
cache:
  pip: true
  apt: true
  directories:
  - devdb
addons:
  sauce_connect: true
  apt:
    packages:
    - poppler-data
    - poppler-utils
    - python-dev
    - python-imaging
    - python-setuptools
    - python-pdftools
    - python-lxml
    - python-simplejson
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt --timeout 30
# command to run tests, e.g. python setup.py test
script:
  - ./manage.py test -v3
  # for the browser tests we need a real db with full data - we rely on cached version to speed up tests
  - if [ ! -f devdb/dev.db ]; then wget http://oknesset-devdb.s3.amazonaws.com/dev.db.bz2; fi
  - if [ ! -f devdb/dev.db ]; then bunzip2 dev.db.bz2 && cp dev.db devdb/dev.db; else cp devdb/dev.db dev.db; fi
  - ./manage.py migrate
  - ./manage.py test --testrunner=knesset.browser_test_runner.Runner --browser=Sauce --full-initialization
